pimcore_data_hub:
    configurations:
        testProducts:
            general:
                active: true
                type: dataImporterDataObject
                name: testProducts
                description: ''
                group: ''
                path: null
                modificationDate: 1678279362
                createDate: 1677060047
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: testProducts/upload.import
            interpreterConfig:
                type: xlsx
                settings:
                    skipFirstRow: true
                    sheetName: Sheet1
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: BigGameProducts
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: findParent
                    settings:
                        findStrategy: id
                        attributeDataObjectClassId: ''
                        attributeName: ''
                        attributeLanguage: ''
                        dataSourceIndex: '2'
                        fallbackPath: '/new Product'
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: 'Brand [0]'
                    dataSourceIndex:
                        - '0'
                    settings:
                        loadStrategy: id
                        attributeDataObjectClassId: ''
                        attributeName: ''
                        attributeLanguage: ''
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Brand
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: id
                                attributeDataObjectClassId: ''
                                attributeName: ''
                                attributeLanguage: ''
                            type: loadDataObject
                -
                    label: 'Category [1]'
                    dataSourceIndex:
                        - '1'
                    settings:
                        loadStrategy: id
                        attributeDataObjectClassId: ''
                        attributeName: ''
                        attributeLanguage: ''
                    transformationResultType: dataObject
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ProductCategory
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: id
                                attributeDataObjectClassId: ''
                                attributeName: ''
                                attributeLanguage: ''
                            type: loadDataObject
                -
                    label: 'Object Name [3]'
                    dataSourceIndex:
                        - '3'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Product Name [4]'
                    dataSourceIndex:
                        - '4'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ProductName
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'SKU [5]'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: SKU
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'UPC [6]'
                    dataSourceIndex:
                        - '6'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: UPC
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Global Trade Item Number [7]'
                    dataSourceIndex:
                        - '7'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GlobalTradeItemNumber
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Thumbnail [8]'
                    dataSourceIndex:
                        - '8'
                    settings:
                        loadStrategy: path
                    transformationResultType: asset
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Thumbnail
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                loadStrategy: path
                            type: loadAsset
                -
                    label: 'Description [9]'
                    dataSourceIndex:
                        - '9'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Description
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Shooting Width [10]'
                    dataSourceIndex:
                        - '10'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.ShootingWidth
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Weight [11]'
                    dataSourceIndex:
                        - '11'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.Weight
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Standing Height [12]'
                    dataSourceIndex:
                        - '12'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.StandingHeight
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Style [13]'
                    dataSourceIndex:
                        - '13'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.Style
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Construction [14]'
                    dataSourceIndex:
                        - '14'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.Construction
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Door [15]'
                    dataSourceIndex:
                        - '15'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.Door
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Height to Bottom of Windows [16]'
                    dataSourceIndex:
                        - '16'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.HeightToBottomOfWindows
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Carrying Bad [17]'
                    dataSourceIndex:
                        - '17'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.CarryingBag
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Window Securing [18]'
                    dataSourceIndex:
                        - '18'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.WindowSecuring
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Stakes [19]'
                    dataSourceIndex:
                        - '19'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.Stakes
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Securing [20]'
                    dataSourceIndex:
                        - '20'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: GroundBlinds.GroundBlinds.Securing
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Price Type [21]'
                    dataSourceIndex:
                        - '21'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: PriceType
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Price [22]'
                    dataSourceIndex:
                        - '22'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Price
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'Availability [23]'
                    dataSourceIndex:
                        - '23'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: Availability
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Item Status [24]'
                    dataSourceIndex:
                        - '24'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ItemStatus
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Scale2 [26]'
                    dataSourceIndex:
                        - '26'
                    settings:
                        unitSourceSelect: static
                        staticUnitSelect: Kilogram
                    transformationResultType: quantityValue
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: scale2
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                unitSourceSelect: static
                                staticUnitSelect: Kilogram
                            type: quantityValue
                -
                    label: 'Scale [25]'
                    dataSourceIndex:
                        - '25'
                    settings:
                        delimiter: ' '
                        keepSubArrays: 'on'
                    transformationResultType: array
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: type
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                delimiter: ' '
                                keepSubArrays: 'on'
                            type: explode
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user:
                    -
                        id: 2
                        name: admin
                        update: true
                        read: true
                        delete: true
                    -
                        id: 13
                        name: Arul
                        read: true
                        update: true
                        delete: true
                    -
                        id: 8
                        name: Hari
                        read: true
                        update: true
                        delete: true
                    -
                        id: 6
                        name: Kishore
                        read: true
                        update: true
                        delete: true
                    -
                        id: 4
                        name: Tanu
                        read: true
                        update: true
                        delete: true
                    -
                        id: 14
                        name: Kasthuri
                        read: true
                        delete: true
                        update: true
                    -
                        id: 3
                        name: Vikash
                        update: true
                        read: true
                        delete: true
                role: {  }
            workspaces: {  }
