pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    content:
                        items: {  }
                        medias: {  }
                        name: content
                        description: ''
                        group: Areas
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1671599986
                        creationDate: 1670307742
                        preserveAnimation: false
