pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    galleryLightbox:
                        items: {  }
                        medias: {  }
                        name: galleryLightbox
                        description: ''
                        group: Areas
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1671605343
                        creationDate: 1671449362
                        preserveAnimation: false
