pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    galleryThumbnail:
                        items: {  }
                        medias: {  }
                        name: galleryThumbnail
                        description: ''
                        group: Areas
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1671599995
                        creationDate: 1671449424
                        preserveAnimation: false
