pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    square500:
                        items: {  }
                        medias: {  }
                        name: square500
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1670236117
                        creationDate: 1670236117
                        preserveAnimation: false
