pimcore:
  workflows:
    workflow:
      label: 'Product Workflow'
      type: 'state_machine'
      supports:
      - 'Pimcore\Model\DataObject\Product'

      places:
        new:
          label: 'New product'
          color: '#377ea9'
          permissions:
          - objectLayout: 1
        rejected:
          label: 'Rejected product'
          color: '#28a013'
        update_content:
          label: 'Update Content'
          title: 'Updating content step'
          color: '#d9ef36'
          permissions:
          - objectLayout: 2

        update_picture:
          label: 'Update Product Picture'
          title: 'Update the product picture'
          color: '#d9ef36'
          permissions:
          - objectLayout: 3
        validate_stock_and_price:
          label: 'Validate Stock + Price'
          title: 'Check the quantity and the price'
          color: '#d9ef36'
          permissions:
          - objectLayout: 4
        content_prepared:
          label: 'Content Prepared'
          title: 'Content ready to publish'
          color: '#28a013'
        accepted:
          label: 'Accepted product'
          color: '#28a013'

      transitions:
        reject_product:
          from: [new, content_prepared]
          to: rejected
          options:
            label: 'Reject the product'
            notes:
              commentEnabled: true
              commentRequired: true
        start_processing:
          from: [new, content_prepared]
          to: update_content
          options:
            label: 'Start processing the product'
            notes:
              commentEnabled: true
              commentRequired: false
        content_updated:
          from: update_content
          to: update_picture
          options:
            label: 'Content up-to-date'
            notes:
              commentEnabled: true
              commentRequired: false
        picture_updated:
          from: update_picture
          to: validate_stock_and_price
          options:
            label: 'Picture up-to-date'
            notes:
              commentEnabled: true
              commentRequired: false
        content_ready:
          from: validate_stock_and_price
          to: content_prepared
          options:
            label: 'Content is ready to publish'
        publish:
          from: content_prepared
          to: accepted
          guard: "is_fully_authenticated() and is_granted('ROLE_PIMCORE_ADMIN')"
          options:
            label: 'Publish the product'
            notes:
              commentEnabled: true
              commentRequired: true
              additionalFields:
              - name: 'timeWorked'
                fieldType: 'input'
                title: 'Time Spent'
                required: true
